---
showSupportUrl:         true
showKnownIssuesUrl:    false
showReleaseNotesUrl:   false
showDonateUrl:         false

requirements:
    requiredRam:        4.0
    requiredDisk:       20.0
    internetCheckUrl:   http://google.com

# Use JARVIS themed icons
branding: jarvis
